name: My Github Workflow

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  my-job1:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
        with:
          python-version: 3.10
      - run: python main.py

 job2:
    # The type of runner that the job will run on
    runs-on: ubantu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python main.py